In [64]:
import cv2
import numpy as np 

In [65]:
valor_gauss = 3
valor_kernel = 5s
#original = cv2.imread('../Images/monedas.jpg')
original = cv2.imread('../Images/monedassoles.jpg')

# imagenes a gris 
gris = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)
# suavisado - desenfoque 
gauss = cv2.GaussianBlur(gris,(valor_gauss, valor_gauss), 0)
#degradado canny deteccion de bordes
canny = cv2.Canny(gauss, 60, 100)
# matriz de unos 
kernel = np.ones((valor_kernel, valor_kernel), np.uint8)
# cierre se enfoca en la imagen principal 
# clausura, limpia el ruido dentro de la imagen 
cierre = cv2.morphologyEx(canny,cv2.MORPH_CLOSE, kernel)

contornos, jerarquia = cv2.findContours(cierre.copy(),cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE )


In [66]:
print("Monedas encontradas: {}".format(len(contornos)))

Monedas encontradas: 10


In [67]:
cv2.drawContours(original,contornos, -1, (255,0,0), 2)

array([[[236, 231, 232],
        [236, 231, 232],
        [236, 231, 232],
        ...,
        [253, 248, 249],
        [253, 248, 249],
        [253, 248, 249]],

       [[236, 231, 232],
        [236, 231, 232],
        [236, 231, 232],
        ...,
        [253, 248, 249],
        [253, 248, 249],
        [253, 248, 249]],

       [[236, 231, 232],
        [236, 231, 232],
        [236, 231, 232],
        ...,
        [253, 248, 249],
        [253, 248, 249],
        [253, 248, 249]],

       ...,

       [[245, 240, 241],
        [245, 240, 241],
        [245, 240, 241],
        ...,
        [255, 250, 251],
        [255, 250, 251],
        [255, 250, 251]],

       [[245, 240, 241],
        [245, 240, 241],
        [245, 240, 241],
        ...,
        [255, 250, 251],
        [255, 250, 251],
        [255, 250, 251]],

       [[245, 240, 241],
        [245, 240, 241],
        [245, 240, 241],
        ...,
        [255, 250, 251],
        [255, 250, 251],
        [255, 250, 251]]

In [68]:
# Mostrar resultados 
#cv2.imshow("Imagen original", original)
#cv2.imshow("Imagen grises", gris)
#cv2.imshow("Imagen Gauss", gauss)
#cv2.imshow("Imagen Canny", canny)
cv2.imshow("Cierre", cierre)
cv2.imshow("Imagen tratada", original)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [69]:
print(np.ones((valor_gauss, valor_gauss),np.uint8))

[[1 1 1]
 [1 1 1]
 [1 1 1]]
